### ISSUE TITLE
和 sduthesis 合并到一起如何？

### ISSUE THREAD

**Issue by Liam0205** [cnDelbert/SDU_thesis_template_for_postgraduate#1]
Hi @cnDelbert 
很高兴终于有人开始维护 SDU 的论文模板了，我毕业多年，已经不太有精力去维护这样的模板。

我有个提议，把你这个模板与我的 sduthesis 合并，以文档类选项的方式，提供学士、硕士、博士论文模板的功能。

**Comment by cnDelbert** [comment]
我也毕业一年了，因为最近师兄要毕业，想要用我的模板，而且我手头没有Windows的电脑，我就趁假期回家整理了一下。
之前学士论文模板和这个研究生的模板差别比较大了，不仅仅是在文档cls里面有区别。
所以，你看下怎么处理能比较好？

<hr>

[这个](https://github.com/cnDelbert/SDUThesis4MasterDegree)是我去年毕业之前弄的，和“SDU_thesis_template_for_postgraduate”还有些不一样。

**Comment by Liam0205** [comment]
我也不用 Windows，不过 LaTeX 跨平台，和是否 Windows 倒是没什么关系。

http://liam0205.me/sduthesis
之前有在这里找了几个还在学校的学弟学妹参与维护，不过看他们似乎热情不高，到现在没什么动静。
所以，这样吧，我把你加入 Liam0205/sduthesis 的维护者，会有有什么需要提交的你也可以直接提交了；然后两个模板合并的事情，我近期抽空合一下。

**Comment by cnDelbert** [comment]
可以的。
