### ISSUE TITLE
newCJKfontfamily编译一直报错

### ISSUE THREAD

**Issue by haolsun** [cnDelbert/SDU_thesis_template_for_postgraduate#2]
! Undefined control sequence.
l.43 ^^I\newCJKfontfamily
                         [fzbighei]{\fzbHei}{方正大黑简体}
?

似乎缺少什么包？我的ctex是2.9.2.164。

**Comment by haolsun** [comment]
介绍里提示“使用 CTeX 套装进行编译，需要 xelatex 和 pdflatex 命令支持。”

经过一天多的研究，xelatex是无法通过编译的。只有使用ctex下Winedt下的PDFTeXify编译器才能通过。

**Comment by duaneya** [comment]
我也遇到这个问题了，用pdflatex可以，但是不知道这样有没有什么隐患

**Comment by duaneya** [comment]
> 介绍里提示 “使用 CTeX 套装进行编译，需要 xelatex 和 pdflatex 命令支持。”
> 
> 经过一天多的研究，xelatex 是无法通过编译的。只有使用 ctex 下 Winedt 下的 PDFTeXify 编译器才能通过。

你最后用这个毕业的吗？

**Comment by haolsun** [comment]
我可能用的是近似的版本，不一定完全一样。

应该是外审结束后有格式审查，版式没啥大问题就行。里面的字体之类的最好不要调。

**Comment by cnDelbert** [comment]
抱歉，毕业太久时间了，TeX和LaTeX也太久不动了。

当时bat编译也是基于当时版本的ctex包进行的，目测xelatex和pdflatex出来的没有差别。

刚看了下，ChenMeng0515和LiamHuang0205的仓库都没有了。如果有问题，可以参考下fork列表，https://github.com/cnDelbert/SDU_thesis_template_for_postgraduate/network/members ，应该有童鞋继续更新了。

祝学业顺利~
