### ISSUE TITLE
错误：File “dtklogos.sty” not found

### ISSUE THREAD

**Issue by Lina-xia** [cnDelbert/SDU_thesis_template_for_postgraduate#6]
在contents/usersettings.tex中有\usepackage{dtklogos}，但并没有相应的.sty文件

**Comment by cnDelbert** [comment]
使用CTeX套装应该有，刚看了下 https://tug.ctan.org/obsolete/usergrps/dante/dtk-1.32/dtklogos.sty 。我这个仓库很老了。
